#!/bin/bash

# Start and stop various versions of ClickHouse. Requires:
#
# *   `clickhousectl` (a.k.a., `chctl`) v0.3.0 or later
# *   `mkdir -p ~/.clickhouse/configs && echo 'timezone: UTC' > ~/.clickhouse/configs/default.yaml`

set -e

usage() {
    cat <<EOF
Usage: runch <command> [<args>]

The runch commands are:
    start [<version>]   Start ClickHouse version; defaults to 26.6
    stop                Stop the current ClickHouse server
    status              Show status of all running severs
    help                Show this usage statement and command summary

EOF
}

name="$(basename "$0")"

case "$1" in
    stop)
        chctl local server stop-all # stop "$name"
        ;;
    start)
        version="${2:-26.6}"

        # cfg_file="$(dirname "$0")/clickhouse.yaml"
        cfg_file=default

        chctl local server stop-all # stop "$name"
        chctl local server start --name "$name" --version "$version" --config-file "$cfg_file"
        ;;
    status)
        chctl local server list
        ;;
    help)
        usage
        ;;
    *)
        test -n "$1" && printf 'Unknown command:  %s\n\n' "$1"
        usage
        exit 1;
        ;;
esac
