name: 🏠 ClickHouse CI
on:
  push:
    branches: [main, wip/**]
  pull_request:
  schedule:
    - cron: "0 13 10 * *" # Monthly at 13:00 on the tenth
permissions:
  contents: read

jobs:
  build:
    env: { pg: 18 }
    strategy:
      fail-fast: false
      matrix:
        # Test latest version and all LTS releases.
        # Keep in sync with dev/docker-compose.yml.
        # .github/ubuntu/ch-versions --lts --latest-stable --earliest 23  --prefix '          - ' | pbcopy
        ch:
          - 26.5.1.882-stable
          - 26.3.11.36-lts
          - 25.8.24.21-lts
          - 25.3.14.14-lts
          - 24.8.14.39-lts
          - 24.3.18.7-lts
          - 23.8.16.40-lts
          - 23.3.22.3-lts
    name: 🏠 ClickHouse ${{ matrix.ch }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Start Postgres
        run: pg-start ${{ env.pg }} libcurl4-openssl-dev uuid-dev liblz4-dev libzstd-dev libre2-dev
      - name: Install Extensions
        run: pgxn install re2
      - name: Checkout the Repository
        uses: actions/checkout@v6
        with: { submodules: true }
      - name: Start ClickHouse
        env: { CH_RELEASE: "${{ matrix.ch }}" }
        run: .github/ubuntu/clickhouse.sh
      - name: Test
        run: pg-build-test
