name: 🏠 ClickHouse CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 13 10 * *" # Monthly at 13:00 on the tenth
jobs:
  build:
    env: { pg: 18 }
    strategy:
      fail-fast: false
      matrix:
        # Test latest version and all LTS releases.
        # Keep in sync with dev/docker-compose.yml.
        # .github/ubuntu/ch-versions --lts --latest-stable --earliest 23  --prefix '          - ' | pbcopy
        ch:
          - 25.12.1.649-stable
          - 25.8.12.129-lts
          - 25.3.10.19-lts
          - 24.8.14.39-lts
          - 24.3.18.7-lts
          - 23.8.16.40-lts
          - 23.3.22.3-lts
    name: 🏠 ClickHouse ${{ matrix.ch }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Start Postgres
        run: pg-start ${{ env.pg }} libcurl4-openssl-dev uuid-dev
      - name: Checkout the Repository
        uses: actions/checkout@v6
        with: { submodules: true }
      - name: Start ClickHouse
        env: { CH_RELEASE: "${{ matrix.ch }}" }
        run: .github/ubuntu/clickhouse.sh
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: vendor/_build/*
          key: vendor-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.git/modules/clickhouse-cpp/refs/heads/master') }}
      # Required to prevent clickhouse-cpp from rebuilding because it depends
      # on this file in the Makefile. https://github.com/actions/checkout/issues/968
      - name: Reset Vendor Timestamp
        run: cd vendor/clickhouse-cpp && touch -d $(git log -1 --format="@%ct" CMakeLists.txt) CMakeLists.txt
      - name: Test DSO
        run: pg-build-test
      - name: Clean
        run: make clean NO_VENDOR_CLEAN=1
      - name: Test Static
        run: pg-build-test
        env: { CH_BUILD: static }
