name: 🔎 Lint
on:
  push:
    branches: [main, wip/**]
  pull_request:
permissions:
  contents: read

jobs:
  lint:
    name: 🔎 Lint Code
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    env: { pg: 18 }
    steps:
      - name: Install Postgres
        run: NO_CLUSTER=1 pg-start ${{ env.pg }} libcurl4-openssl-dev uuid-dev clang-tidy
      - name: Install clang-format # version in Ubuntu is too old
        run: curl -sLo /usr/local/bin/clang-format https://github.com/cpp-linter/clang-tools-static-binaries/releases/latest/download/clang-format-22_linux-amd64 && chmod +x /usr/local/bin/clang-format
      - name: Checkout the Repository
        uses: actions/checkout@v6
      - name: Install pre-commit
        run: make debian-install-lint
      - name: Install Tools
        run: apt-get update && apt-get install -y bear clang-tidy
      - name: Add Postgres to Path
        run: echo /usr/lib/postgresql/${{ env.pg }}/bin >> "$GITHUB_PATH"
      - name: Initialize Submodules
        run: git submodule update --init
      - name: Generate compile_commands.json
        run: make compile_commands.json
      - name: Lint the Code
        run: make lint
