name: 🚀 Bundle & Release
on:
  push:
    branches: [main, wip/**]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
permissions:
  contents: write
jobs:
  release:
    name: Release on GitHub and PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Start Postgres
        run: pg-start 18 libcurl4-openssl-dev uuid-dev liblz4-dev libzstd-dev
      - name: Start ClickHouse
        env: { CH_RELEASE: "${{ matrix.ch }}" }
        run: .github/ubuntu/clickhouse.sh
      - name: Bundle the Release
        env: { GIT_ARCHIVE_CMD: archive-all }
        id: bundle
        run: pgxn-bundle
      - name: Test the Bundle
        env: { PGUSER: postgres }
        run: make dist-test
      - name: Release on PGXN
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release
      - name: Generate Release Notes
        id: notes
        uses: theory/changelog-version-notes-action@v0
        if: startsWith( github.ref, 'refs/tags/v' )
      - name: Create GitHub Release
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body_path: "${{ steps.notes.outputs.file }}"
          files: ${{ steps.bundle.outputs.bundle }}
